receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: http://host.docker.internal:8080
    tls:
      insecure: true
    headers:
      Content-Type: application/json
      Authorization: ApiKey L0gg|3K3y
      X-Loggle-Key: L0gg|3K3y
    encoding: proto
    compression: none

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug, otlphttp]
