name: 'C# linting'
on:
  pull_request:
    paths: ['src/**.cs']
    branches: [ 'release/*', 'master']

permissions:
  pull-requests: read

jobs:
  lint-csharp:
    if: contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.pull_request.author_association)
    name: 'C# Linting'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: CI_BUILD_TOKEN
